---
title: Analyse the dataset
---

## Preamble and sampling

In [25]:
import nltk
import polars as pl

from collections import Counter
from datasets import load_dataset
from nltk.tokenize import word_tokenize

In [22]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
load_dataset("roneneldan/TinyStories", split="train").to_parquet("tinystories.parquet")
load_dataset("SimpleStories/SimpleStories", split="train").to_parquet("simplestories.parquet")

In [38]:
tinystories_df = pl.scan_parquet("tinystories.parquet")
tinystories_df.head().collect()

shape: (5, 1)
┌─────────────────────────────────┐
│ text                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ One day, a little girl named L… │
│ Once upon a time, there was a … │
│ One day, a little fish named F… │
│ Once upon a time, in a land fu… │
│ Once upon a time, there was a … │
└─────────────────────────────────┘

In [34]:
simplestories_df = pl.scan_parquet("simplestories.parquet")
simplestories_df.head().collect()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ story     ┆ topic     ┆ theme     ┆ style     ┆ … ┆ num_stori ┆ expected_ ┆ generatio ┆ model    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ es_in_com ┆ num_stori ┆ n_id      ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ pletion   ┆ es_in_com ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ple…      ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Eagerly,  ┆ subterran ┆ Hardship  ┆ lighthear ┆ … ┆ 11        ┆ 12        ┆ 7482221ff ┆ gpt-4o-m │
│ a girl    ┆ ean       ┆           ┆ ted       ┆   ┆           ┆           ┆ 291ce5936 ┆ ini-2024 │
│ named Kim ┆ worlds    ┆           ┆           ┆   ┆           ┆           ┆ eccc77c70 ┆ -07-18   │
│ went…     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0d9…      ┆          │
│ Key       ┆ shape-shi ┆ Failure   ┆ playful   ┆ … ┆ 6         ┆ 6         ┆ 940305166 ┆ gpt-4o-m │
│ turned in ┆ fting     ┆           ┆           ┆   ┆           ┆           ┆ 197525600 ┆ ini-2024 │
│ the old   ┆           ┆           ┆           ┆   ┆           ┆           ┆ cfc5fcbbb ┆ -07-18   │
│ lock. A … ┆           ┆           ┆           ┆   ┆           ┆           ┆ 513…      ┆          │
│ Rain      ┆ seasonal  ┆ Friendshi ┆ humorous  ┆ … ┆ 4         ┆ 5         ┆ 315219dcf ┆ gpt-4o-m │
│ poured    ┆ changes   ┆ p         ┆           ┆   ┆           ┆           ┆ 08e931023 ┆ ini-2024 │
│ down on   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 50aebb412 ┆ -07-18   │
│ the tiny  ┆           ┆           ┆           ┆   ┆           ┆           ┆ a2c…      ┆          │
│ t…        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ An old    ┆ virtual   ┆ Discovery ┆ whimsical ┆ … ┆ 11        ┆ 12        ┆ 1a854e00b ┆ gpt-4o-m │
│ tree      ┆ worlds    ┆           ┆           ┆   ┆           ┆           ┆ 6750677b6 ┆ ini-2024 │
│ stood     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 856a0be05 ┆ -07-18   │
│ tall in a ┆           ┆           ┆           ┆   ┆           ┆           ┆ 30e…      ┆          │
│ fo…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Truthfull ┆ gardens   ┆ Contradic ┆ suspensef ┆ … ┆ 4         ┆ 4         ┆ 5f5524c5a ┆ gpt-4o-m │
│ y, the    ┆           ┆ tion      ┆ ul        ┆   ┆           ┆           ┆ 3ac334bdb ┆ ini-2024 │
│ garden    ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6c576e531 ┆ -07-18   │
│ was a p…  ┆           ┆           ┆           ┆   ┆           ┆           ┆ 304…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Length comparison

In [40]:
tinystories_df = tinystories_df.with_columns(
    pl.col("text").str.split(" ").list.len().alias("word_count")
)



tinystories_df.head().collect()

shape: (5, 2)
┌─────────────────────────────────┬────────────┐
│ text                            ┆ word_count │
│ ---                             ┆ ---        │
│ str                             ┆ u32        │
╞═════════════════════════════════╪════════════╡
│ One day, a little girl named L… ┆ 132        │
│ Once upon a time, there was a … ┆ 140        │
│ One day, a little fish named F… ┆ 166        │
│ Once upon a time, in a land fu… ┆ 161        │
│ Once upon a time, there was a … ┆ 127        │
└─────────────────────────────────┴────────────┘