---
title: Analyse the dataset
---

## Preamble and sampling

In [2]:
import nltk
import polars as pl

from collections import Counter
from datasets import load_dataset
from nltk.tokenize import word_tokenize

/home/ubuntu/miniconda/envs/py311/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [19]:
nltk.download("punkt")
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/ubuntu/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [4]:
load_dataset("roneneldan/TinyStories", split="train").to_parquet("tinystories.parquet")
load_dataset("SimpleStories/SimpleStories", split="train").to_parquet("simplestories.parquet")

Generating train split: 100%|██████████| 2119719/2119719 [00:49<00:00, 42556.77 examples/s]
Generating validation split: 100%|██████████| 21990/21990 [00:00<00:00, 35415.33 examples/s]
Creating parquet from Arrow format: 100%|██████████| 20/20 [01:07<00:00,  3.37s/ba]
Generating train split: 100%|██████████| 2115696/2115696 [01:25<00:00, 24812.86 examples/s]
Generating test split: 100%|██████████| 21371/21371 [00:00<00:00, 24912.86 examples/s]
Creating parquet from Arrow format: 100%|██████████| 32/32 [01:47<00:00,  3.34s/ba]

3142783327

In [7]:
tinystories_df = pl.scan_parquet("tinystories.parquet")
tinystories_df.head().collect()

shape: (5, 1)
┌─────────────────────────────────┐
│ text                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ One day, a little girl named L… │
│ Once upon a time, there was a … │
│ One day, a little fish named F… │
│ Once upon a time, in a land fu… │
│ Once upon a time, there was a … │
└─────────────────────────────────┘

In [8]:
simplestories_df = pl.scan_parquet("simplestories.parquet")
simplestories_df.head().collect()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ story     ┆ topic     ┆ theme     ┆ style     ┆ … ┆ num_stori ┆ expected_ ┆ generatio ┆ model    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ es_in_com ┆ num_stori ┆ n_id      ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ pletion   ┆ es_in_com ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ple…      ┆ str       ┆          │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Eagerly,  ┆ subterran ┆ Hardship  ┆ lighthear ┆ … ┆ 11        ┆ 12        ┆ 7482221ff ┆ gpt-4o-m │
│ a girl    ┆ ean       ┆           ┆ ted       ┆   ┆           ┆           ┆ 291ce5936 ┆ ini-2024 │
│ named Kim ┆ worlds    ┆           ┆           ┆   ┆           ┆           ┆ eccc77c70 ┆ -07-18   │
│ went…     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0d9…      ┆          │
│ Key       ┆ shape-shi ┆ Failure   ┆ playful   ┆ … ┆ 6         ┆ 6         ┆ 940305166 ┆ gpt-4o-m │
│ turned in ┆ fting     ┆           ┆           ┆   ┆           ┆           ┆ 197525600 ┆ ini-2024 │
│ the old   ┆           ┆           ┆           ┆   ┆           ┆           ┆ cfc5fcbbb ┆ -07-18   │
│ lock. A … ┆           ┆           ┆           ┆   ┆           ┆           ┆ 513…      ┆          │
│ Rain      ┆ seasonal  ┆ Friendshi ┆ humorous  ┆ … ┆ 4         ┆ 5         ┆ 315219dcf ┆ gpt-4o-m │
│ poured    ┆ changes   ┆ p         ┆           ┆   ┆           ┆           ┆ 08e931023 ┆ ini-2024 │
│ down on   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 50aebb412 ┆ -07-18   │
│ the tiny  ┆           ┆           ┆           ┆   ┆           ┆           ┆ a2c…      ┆          │
│ t…        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ An old    ┆ virtual   ┆ Discovery ┆ whimsical ┆ … ┆ 11        ┆ 12        ┆ 1a854e00b ┆ gpt-4o-m │
│ tree      ┆ worlds    ┆           ┆           ┆   ┆           ┆           ┆ 6750677b6 ┆ ini-2024 │
│ stood     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 856a0be05 ┆ -07-18   │
│ tall in a ┆           ┆           ┆           ┆   ┆           ┆           ┆ 30e…      ┆          │
│ fo…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Truthfull ┆ gardens   ┆ Contradic ┆ suspensef ┆ … ┆ 4         ┆ 4         ┆ 5f5524c5a ┆ gpt-4o-m │
│ y, the    ┆           ┆ tion      ┆ ul        ┆   ┆           ┆           ┆ 3ac334bdb ┆ ini-2024 │
│ garden    ┆           ┆           ┆           ┆   ┆           ┆           ┆ 6c576e531 ┆ -07-18   │
│ was a p…  ┆           ┆           ┆           ┆   ┆           ┆           ┆ 304…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Length comparison

In [9]:
tinystories_df = tinystories_df.with_columns(
    pl.col("text").str.split(" ").list.len().alias("word_count")
)
tinystories_df.head().collect()

shape: (5, 2)
┌─────────────────────────────────┬────────────┐
│ text                            ┆ word_count │
│ ---                             ┆ ---        │
│ str                             ┆ u32        │
╞═════════════════════════════════╪════════════╡
│ One day, a little girl named L… ┆ 132        │
│ Once upon a time, there was a … ┆ 140        │
│ One day, a little fish named F… ┆ 166        │
│ Once upon a time, in a land fu… ┆ 161        │
│ Once upon a time, there was a … ┆ 127        │
└─────────────────────────────────┴────────────┘

In [30]:
from readability import Readability

text

NameError: name 'text' is not defined

In [28]:
from readability import Readability

def calculate_flesch_kincaid_score(text):
    r = Readability(text)
    result = r.flesch_kincaid(min_words=10)
    return result.score

calculate_flesch_kincaid_score(tinystories_df.head().collect().item(1, "text"))

tinystories_df.with_columns(
    pl.col("text").map_elements(calculate_flesch_kincaid_score, return_dtype=pl.Float64)
        .alias("flesch_kincaid_score")
).collect()

TypeError: Readability.flesch_kincaid() got an unexpected keyword argument 'min_words'

In [14]:
ts_result = tinystories_df.select(
    word_count_mean = pl.col("word_count").mean(),
    word_count_std = pl.col("word_count").std(),
    
)
ts_result.collect()

shape: (1, 2)
┌─────────────────┬────────────────┐
│ word_count_mean ┆ word_count_std │
│ ---             ┆ ---            │
│ f64             ┆ f64            │
╞═════════════════╪════════════════╡
│ 171.832831      ┆ 77.416249      │
└─────────────────┴────────────────┘

In [15]:
ts_result